version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: thursday-session-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: thursday-session-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data: 